who = [
    "sister",
    "brother",
    "mother",
    "father",
    "parents",
    "siblings",
    "grandparents",
    "teacher",
    "nurse",
    "undertaker",
    "policeman",
    "doctor",
    "professor",
    "scientist",
    "salesman",
    "youtuber",
    "priest",
    "nun",
    "demon",
    "ghost",
    "boogeyman",
    "werewolf",
    "vampire",
    "kidnappers",
    "clown",
    "aliens",
    "garden gnomes",
    "gargoyles",
    "Pope",
    "President",
    "Prime Minister",
    "fishmonger",
    "bar wench",
]

who_adjectives = [
    "smelly",
    "dark",
    "mad",
    "crazy",
    "brooding",
    "creepy",
    "mysterious",
    "silent",
    "blind",
    "mute",
    "dead",
    "infected",
    "ugly",
    "beautiful",
    "mesmerising",
    "insane",
    "inebriated",
    "adorable",
    "aggressive",
    "amused",
    "difficult",
    "hungry",
    "defiant",
    "repulsive",
    "smiling",
    "grinning",
    "eviscerated",
    "mutilated",
    "sparkling",
    "evil",
]